version: 2
formats: "all"
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
python:
   install:
   - requirements: "requirements_dev.txt"
   - path: "."
sphinx:
   configuration: "docs/conf.py"
